[BACK-2019] Update data model to support uploading Tidepool Loop settings
tidepool-org/platform pull request #580
Opened 2021-11-11 21:23 UTC by darinkrauss

- https://tidepool.atlassian.net/browse/BACK-2019
- Update pumpSettings with new fields
- Update cgmSettings with new fields
- Add controllerSettings
- Add deviceEvent/pumpSettingsOverride
- Remove applicationSettings
- Tests

2021-11-17 13:26 UTC, toddkazakov requested changes
Overall looks good. I think you should just rename the functions which generate random data instead of deprecating them, because this only adds tech debt.

2021-11-18 20:08 UTC, darinkrauss commented on data/types/settings/cgm/cgm.go
> +	if normalizer.Origin() == structure.OriginExternal {
Yes, I see. I will combine.

2021-11-18 20:17 UTC, darinkrauss commented on data/types/settings/cgm/cgm.go
> +	if normalizer.Origin() == structure.OriginExternal {
Done.

2021-11-18 20:17 UTC, darinkrauss commented
@toddkazakov  I removed the deprecated New* test functions that I changed.

2021-11-18 20:40 UTC, toddkazakov requested changes
There are few more deprecated functions that should be renamed instead of deprecated

2021-11-18 20:40 UTC, toddkazakov commented on data/blood/glucose/test/target.go
> +// DEPRECATED: Use RandomTarget
This should be renamed instead of deprecated

2021-11-18 20:40 UTC, toddkazakov commented on data/types/device/test/device.go
> +// DEPRECATED: Use RandomDevice
This should be renamed instead of deprecated

2021-11-18 20:40 UTC, toddkazakov commented on data/types/test/base.go
> +// DEPRECATED: Use RandomBase
This should be renamed instead of deprecated

2021-11-18 21:11 UTC, darinkrauss commented
@toddkazakov Sorry, my bad. I made the changes to a different branch and pushed that. Will move to this branch and re-request review.

2021-11-18 22:05 UTC, darinkrauss commented
@toddkazakov Okay, commits added here. Should be good now.

2021-11-19 17:52 UTC, toddkazakov approved these changes
LGTM 👍

2022-01-12 19:22 UTC, ginnyyadav commented
/deploy qa2

2022-02-07 19:51 UTC, merged