[BACK-1758] Move data with type=upload to its own collection.
tidepool-org/platform pull request #629
Opened 2023-03-08 17:56 UTC by lostlevels

Move deviceData with type='upload' to its own collection named deviceDataSets

which acts as a collection for "parent" datum where its children are in the original deviceData collection. Split platform/data/store.DataRepository into 2 repositories, one for DataSet and one for data of these DataSets called DataSetRepository and DatumRepository, respectively.

2023-04-05 12:04 UTC, toddkazakov reviewed
@lostlevels ~~If I understand correctly, when we deploy this PR we'll only write to and read from the new collection. Let's say there's a request for fetching an upload record by id that's been created before those changes. The record will only be present in the old collection, thus the request will return 404. Shouldn't the calling functions of the repositories fall back to the old collection for all reads?~~

Ignore my stupid comment above. Github didn't expand the diff of mongo_data.go and I assumed it's only deletions. Reviewing now.

2023-04-05 12:29 UTC, toddkazakov requested changes
Everything looks good, except the two methods which ought to list all data sets for a given user. Currently, if there are any data sets in the new collection those methods return the results only from the new collection, ignoring all data in the old collection. I think results from both collections should be merged instead.

2023-04-05 12:29 UTC, toddkazakov commented on data/store/mongo/mongo_data.go
> +		return dataSets, nil
Instead of returning early shouldn't you merge results from both collections?

2023-04-05 12:29 UTC, toddkazakov commented on data/store/mongo/mongo_data.go
> +		return dataSets, nil
Instead of returning early shouldn't you merge results from both collections?

2023-06-09 16:13 UTC, lostlevels commented
/deploy qa2 data

2023-06-15 22:14 UTC, lostlevels commented
Squashed commits because rebasing with master was getting funky even with rerere.

2023-08-09 09:58 UTC, toddkazakov approved these changes

2023-08-09 22:42 UTC, merged