back-37 testing and addition of back-2773
tidepool-org/platform pull request #688
Opened 2023-12-19 20:53 UTC by jh-bate

moving in work from developer testing

2024-04-26 23:33 UTC, darinkrauss requested changes
Okay, finally finished. Lots of comments with some probably needing a change and others maybe not.

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/data_migration.go
> +		err = errors.Join(err, errors.New("missing required settings"))
Why not just return the errors here rather than using a local variable?

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/data_migration.go
> +		err = errors.Join(err, errors.New("missing required settings"))
BTW, do we want to check `dataC`, too?

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/data_migration.go
> +	lastUpdatedID        string
Suggest you just make this a `*string` to avoid any of the `pointer.String` stuff.

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/data_migration.go
> +	lastUpdatedID        string
Besides, when not using a pointer, the default is an empty string, which you have a special case to check for in `jellyfishQuery`. Just use a pointer and get rid of an empty string logic.

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/data_migration.go
> +func (m *DataMigration) writeAudit(groupLimit *int) {
Is groupLimit actually used by any callers?

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/data_migration.go
> +func (m *DataMigration) writeErrors(groupLimit *int) {
Is groupLimit actually used by any callers?

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/data_migration.go
> +		defer f.Close()
This will leave all of the files open until the function exits. It won't close each file after it is written to (which I think was your intention).

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/data_migration.go
> +	if m.settings.StopOnErr {
@You can probably put this block at the top of the function.

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/data_migration.go
> +		log.Printf("processed %.0f %% of %d records and applied %d changes", percent, *capacity, stats.Applied)
Would we want a log message for when `capacity == nil`, too? Just without the capacity and percent?

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/data_migration.go
> +	queryFn DataMigrationQueryFn,
Using functions a bit harder to understand, but okay, I suppose. This is for testing right? Next time consider interfaces.

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/jellyfish_data.go
> +	}
```suggestion
	var selector bson.M
	if settings.Rollback {
		selector = bson.M{
			settings.RollbackSectionName: bson.M{"$exists": true},
		}
	} else {
		selector = bson.M{
  		    "_deduplicator": bson.M{"$exists": false},
		}
	}
```

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/jellyfish_data.go
> +							Filter:   bson.M{"_id": itemID, "modifiedTime": item["modifiedTime"]},
Modified time is so we don't stop on other changes happening simultaneously-ish?

2024-04-26 23:33 UTC, darinkrauss commented on migrations/20231128_jellyfish_migration/utils/jellyfish_data.go
> +							Filter:   bson.M{"_id": itemID, "modifiedTime": item["modifiedTime"]},
So, I guess if this happens ad an update is excluded because it changed by something else, we'd pick this up on the next go around?

2024-09-16 22:00 UTC, jh-bate commented
supersedded by #741

2024-09-16 22:01 UTC, jh-bate commented
superseded by https://github.com/tidepool-org/platform/pull/741

2024-09-16 22:01 UTC, closed without merging