Clean up some remaining dual reads for datasets.
tidepool-org/platform pull request #696
Opened 2024-02-06 20:42 UTC by lostlevels

Since all uploads are already migrated, this does not change the existing output of any function. As spotted by @Roukoswarf

2024-02-07 22:37 UTC, darinkrauss requested changes
LGTM, but I defer to @Roukoswarf for confirmation that all data sets are in the `DataSetRepository` and approval.

2024-02-07 22:37 UTC, darinkrauss commented on data/store/mongo/mongo_data.go
> +func (d *DataRepository) GetDataSetByID(ctx context.Context, uploadID string) (*upload.Upload, error) {
[nit] Please stick with `dataSetID` as `uploadID` is really an "old" term.

2024-02-07 22:37 UTC, darinkrauss commented on data/store/mongo/mongo_data_set.go
> +func (d *DataSetRepository) GetDataSetByID(ctx context.Context, uploadID string) (*upload.Upload, error) {
[nit] Please stick with `dataSetID` as `uploadID` is really an "old" term.

2024-02-07 22:37 UTC, darinkrauss commented on data/store/mongo/mongo_data.go
> +func (d *DataRepository) GetDataSet(ctx context.Context, uploadID string) (*data.DataSet, error) {
[nit] Please stick with `dataSetID` as `uploadID` is really an "old" term.

2024-02-07 22:37 UTC, darinkrauss commented on data/store/mongo/mongo_data_set.go
> +func (d *DataSetRepository) GetDataSet(ctx context.Context, uploadID string) (*data.DataSet, error) {
[nit] Please stick with `dataSetID` as `uploadID` is really an "old" term.

2024-02-07 22:37 UTC, darinkrauss commented on data/store/store.go
> +	GetDataSetByID(ctx context.Context, uploadID string) (*upload.Upload, error)
[nit] Please stick with `dataSetID` as `uploadID` is really an "old" term.

2024-02-07 22:37 UTC, darinkrauss commented on data/store/store.go
> +	GetDataSet(ctx context.Context, uploadID string) (*data.DataSet, error)
[nit] Please stick with `dataSetID` as `uploadID` is really an "old" term.

2024-02-09 18:57 UTC, darinkrauss approved these changes
LGTM!

2024-03-26 19:38 UTC, Roukoswarf approved these changes
Looks good

2024-05-06 15:12 UTC, merged