[BACK-2638] Move Summary buckets to collection and unify datastructure
tidepool-org/platform pull request #763
Opened 2024-09-04 02:02 UTC by Roukoswarf

2025-01-13 22:57 UTC, Roukoswarf commented on data/store/mongo/mongo_summary.go
> +	//	},
TODO: create proper indexes and uncomment this

2025-02-07 11:31 UTC, toddkazakov commented on data/summary/test/test_suite_test.go
> +package test_test
You're breaking the convention here - the `test` package ought to contain only test helper functions (e.g. to generate data), not actual Ginkgo Tests

2025-02-07 11:47 UTC, toddkazakov commented on data/summary/types/glucose.go
> +	bucket := &Bucket[*GlucoseBucket, GlucoseBucket]{}
You’re defining the bucket here and it has attributes which have omitempty. This means that the attributes won’t be serialized in the mongo document. Subsequently when such bucket is deserialized the deserializer for the attribute won’t be called.

Imagine processing the following mongo documents:
```
{
  data: {
    total: {
      glucose: 5
    }
  }
},
{
  data: {
    total: {
    }
  }
}
```

and you define the bucket before its intended scope of use:
```
bucket := &Bucket[*GlucoseBucket, GlucoseBucket]{}
for bucketsCursor.Next(ctx) {
  if err := bucketsCursor.Decode(bucket); err != nil {
    return err
  }
  // You're only using the bucket here
  fmt.Println(bucket.Data.Total.Glucose)
}
```

The above code will print
```
5
5
```

Instead of the actual values that were used before persisting the structs in mongo:
```
5
0
```

2025-02-07 11:55 UTC, toddkazakov commented on data/summary/types/util.go
> +	if dataSet.Type != continuous.Type {
```suggestion
	if datum.Type != continuous.Type {
```

2025-03-11 20:52 UTC, Roukoswarf commented
/deploy qa2 data

2025-03-17 12:52 UTC, toddkazakov requested changes
Left feedback inline - overall looks good, but there are few issues

2025-03-17 12:52 UTC, toddkazakov commented on data/summary/types/glucose.go
> +type Range struct {
Remove `omitempty` to avoid bugs

2025-03-17 12:52 UTC, toddkazakov commented on data/summary/types/glucose.go
> +	LastRecordDuration int `json:"lastRecordDuration,omitempty" bson:"lastRecordDuration,omitempty"`
Remove `omitempty` to avoid bugs

2025-03-17 12:52 UTC, toddkazakov commented on data/summary/types/glucose.go
> +type GlucosePeriod struct {
Remove `omitempty` to avoid bugs

2025-03-17 12:52 UTC, toddkazakov commented on data/summary/test/generators.go
> +package test
Move under `data/test`

2025-03-17 12:52 UTC, toddkazakov commented on data/summary/test/summary.go
> +package test
Move under `data/test`

2025-03-18 08:26 UTC, toddkazakov commented on data/client/client.go
> +	types2 "github.com/tidepool-org/platform/summary/types"
Rename to `summaryTypes` for consistency

2025-05-12 21:33 UTC, merged